routes:

collections:
  /:
    permalink: /{slug}/
    template: index

  /post/:
    permalink: /{slug}/
    template: post

  /experts/:
    permalink: /{slug}/
    template: experts

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
